### ISSUE TITLE
'prefers-reduced-motion' and transition-duration: 0s 

### ISSUE THREAD

**Issue by ciar4n** [onokumus/metismenujs#9]
**Describe the bug**
Appears to be an issue if the following is part of the CSS and reduced motion is enabled on the OS...

```css

@media (prefers-reduced-motion: reduce) { 
   *, ::before, ::after { 
     transition-duration: 0s !important; 
   } 
 }
```

The first event on the menu works fine but after that, nothing, the menu completely freezes up with no errors. Strangely works fine if `transition-duration: 0.000000001s`, just not with `transition-duration: 0s`

**Expected behavior**
Menu works fine with no animations

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser CHrome / Firefox (latest)
 - Latest
